/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.utilities

import org.example.list.LinkedList

class StringUtils {
    companion object {
        /**
         * Concatenates the elements of the given linked list into a single string.
         *
         * The elements are converted to strings and combined in the order they appear in
         * the list.
         *
         * @param source The linked list whose elements will be joined.
         * @return The resulting string produced by joining the list elements.
         */
        fun join(source: LinkedList): String {
            return JoinUtils.join(source)
        }

        /**
         * Split a string into a LinkedList of substrings.
         *
         * Returns a LinkedList containing the substrings in the original order.
         *
         * @param source The string to split.
         * @return A LinkedList of substrings produced from the input.
         */
        fun split(source: String): LinkedList {
            return SplitUtils.split(source)
        }
    }
}
